language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=PSR2 src

after_script:
  - php vendor/bin/coveralls -v
