language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=phpcs.xml src
